version: "3.9"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
    - ./files:/app/files
    container_name: api
    ports:
      - "5159:5159"
    environment:
      ASPNETCORE_URLS: http://+:5159
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=app;Username=postgres;Password=postgres
      FilesRoot: /app/files
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: next
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://api:5159
    depends_on:
      - api

  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
